# fastlane/Fastfile
default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
    import_certificate(
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
      keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"],
      certificate_path: 'Certificates.p12',
      certificate_password: ENV["CERTIFICATE_PASSWORD"] || "default"
    ) 
    puts "Its working here"
    end

  private_lane :prepare_certificates do |options|
    sh("base64 -D -o Certificates.p12 <<< \"#{ENV['Certificates']}\"", log: false)
    create_keychain(
        name: "default_keychain",
        default_keychain: true,
        unlock: true,
        password: "default"
    )
    import_certificate(
      certificate_path: "Certificates.p12",
      certificate_password: ENV['CERTIFICATE_PASSWORD'],
      keychain_name: "default_keychain",
      keychain_password: "default"
    )

    unlock_keychain(path:"default_keychain", password:"default")
    sh "security set-keychain-settings -t 3600 -l ~/Library/Keychains/default_keychain-db"

  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Ad-hoc build"
  lane :adhoc do
    match(type: "adhoc",readonly: false)
    gym(export_method: "ad-hoc")
  end

  lane :beta do
    build_app(scheme: "Game")
    upload_to_testflight
  end

end